import Table from "@mui/material/Table";
import TableBody from "@mui/material/TableBody";
import TableCell from "@mui/material/TableCell";
import TableContainer from "@mui/material/TableContainer";
import TableHead from "@mui/material/TableHead";
import TableRow from "@mui/material/TableRow";
import Paper from "@mui/material/Paper";
import styles from "./List.module.css";
import { useSelector } from "react-redux";

export const List = () => {
  const darkMode = useSelector((state) => state.darkMode.darkMode);

  const rows = [
    {
      id: 1143155,
      product: "Acer Nitro 5",
      img: "https://m.media-amazon.com/images/I/81bc8mA3nKL._AC_UY327_FMwebp_QL65_.jpg",
      admin: "Kitiibwa Deo",
      date: "1 March",
      role: "Admin",
      generatedBy: "Emmanuella",
      status: "Approved",
    },
    {
      id: 2235235,
      product: "Playstation 5",
      img: "https://m.media-amazon.com/images/I/31JaiPXYI8L._AC_UY327_FMwebp_QL65_.jpg",
      admin: "Luwuge Robert",
      date: "1 March",
      role: "Super admin",
      generatedBy: "You",
      status: "Pending",
    },
    {
      id: 2342353,
      product: "Redragon S101",
      img: "https://m.media-amazon.com/images/I/71kr3WAj1FL._AC_UY327_FMwebp_QL65_.jpg",
      admin: "Ninsiima Timothy",
      date: "1 March",
      role: "Admin",
      generatedBy: "You",
      status: "Pending",
    },
    {
      id: 2357741,
      product: "Razer Blade 15",
      img: "https://m.media-amazon.com/images/I/71wF7YDIQkL._AC_UY327_FMwebp_QL65_.jpg",
      admin: "Atwiine Martha",
      date: "1 March",
      role: "Admin",
      generatedBy: "Atuhairwe Wycliffe",
      status: "Approved",
    },
    {
      id: 2342355,
      product: "ASUS ROG Strix",
      img: "https://m.media-amazon.com/images/I/81hH5vK-MCL._AC_UY327_FMwebp_QL65_.jpg",
      admin: "Atukwase Leon",
      date: "1 March",
      role: "Admin",
      generatedBy: "Namitala Theresa",
      status: "Pending",
    },
  ];
  return (
    <TableContainer
      component={Paper}
      className={`${styles["table"]} ${darkMode && styles["darkmode-table"]}`}
    >
      <Table sx={{ minWidth: 650 }} aria-label="simple table">
        <TableHead>
          <TableRow>
            <TableCell className={styles["tableCell"]}>Admin token</TableCell>
            {/* <TableCell className={styles["tableCell"]}>Product</TableCell> */}
            <TableCell className={styles["tableCell"]}>Name</TableCell>
            <TableCell className={styles["tableCell"]}>Date</TableCell>
            <TableCell className={styles["tableCell"]}>Role</TableCell>
            <TableCell className={styles["tableCell"]}>Generated by</TableCell>
            <TableCell className={styles["tableCell"]}>Status</TableCell>
          </TableRow>
        </TableHead>
        <TableBody>
          {rows.map((row) => (
            <TableRow key={row.id}>
              <TableCell
                className={`${styles["tableCell"]} ${
                  darkMode && styles["darkmode-table"]
                }`}
              >
                {row.id}
              </TableCell>
              {/* <TableCell className={styles["tableCell"]}>
                <div className={styles["cellWrapper"]}>
                  <img src={row.img} alt="" className={styles["image"]} />
                  {row.product}
                </div>
              </TableCell> */}
              <TableCell
                className={`${styles["tableCell"]} ${
                  darkMode && styles["darkmode-table"]
                }`}
              >
                {row.admin}
              </TableCell>
              <TableCell
                className={`${styles["tableCell"]} ${
                  darkMode && styles["darkmode-table"]
                }`}
              >
                {row.date}
              </TableCell>
              <TableCell
                className={`${styles["tableCell"]} ${
                  darkMode && styles["darkmode-table"]
                }`}
              >
                {row.role}
              </TableCell>
              <TableCell
                className={`${styles["tableCell"]} ${
                  darkMode && styles["darkmode-table"]
                }`}
              >
                {row.generatedBy}
              </TableCell>
              <TableCell
                className={`${styles["tableCell"]} ${
                  darkMode && styles["darkmode-table"]
                }`}
              >
                <span className={`${styles["status"]} ${styles[row.status]}`}>
                  {row.status}
                </span>
              </TableCell>
            </TableRow>
          ))}
        </TableBody>
      </Table>
    </TableContainer>
  );
};
